package svg

import (
  "os"
  "github.com/sleepydog1214/svg-generator/check"
  "github.com/sleepydog1214/svg-generator/defs"
)

func PrintHeader (fp *os.File, fname string) () {
  header := `<?xml version="1.0" encoding="UTF-8" standalone="no"?>` + "\n" +
             `<svg ` + "\n" +
             ` version="1.1"` + "\n" +
             ` width="` + defs.Params["maxWidth"] + `"` + "\n" +
             ` height="` + defs.Params["maxHeight"] + `"` + "\n" +
             ` viewBox="0 0 ` + defs.Params["maxX"] + " " + defs.Params["maxY"] + `">` + "\n" +
             `<title>TS Art Random SVG Image ` + fname + `</title>` + "\n" +
             `<desc>Randomly generated by Thomas Suchyta</desc>` + "\n"

  _, err := fp.WriteString(header)
  check.Error(err)
}

func PrintFooter (fp *os.File) () {
  footer := `<\svg>`

  _, err := fp.WriteString(footer)
  check.Error(err)
}
